### PR TITLE
Add a progress bar for downloads.

### PR DESCRIPTION
**Pull request by dsully**

### CODE REVIEW

**Comment by Narsil** [comment]
Hi thanks for this PR.

I'm not really sure we should add this. It is a good crate, but indicatif doesn't really play well with non shell environments, colab/jupyter most notably.

Also it would have to be checked, but printing anything has a cost, and we would need to triple check that we're not slowing things down by doing this (The higher the bandwidth, the higher the risk of slowdown, which is the best case for this package).

(For reference: https://github.com/npm/npm/issues/11283)

We could also make it optional, but I don't feel it's worth the complexity. This is a very specific package for a very specific use case, and shouldn't IMO try to be a one size fits all. I think it's perfectly fine to not display a progressbar.

**Comment by McPatate** [comment]
> but printing anything has a cost

We could simply create an MPSC channel where in `download_chunk` you write the content length and in the consumer you write the progress bar (so separate thread, which should not slow down the download noticeably).
cf https://github.com/McPatate/lfs-cta-rs/blob/trunk/src/main.rs#L308-L335

I'm pretty sure it wouldn't be too hard to make it optional and I believe it adds value: you have visual confirmation your download **is** occuring and you have data regarding its speed.

While we're at it, we could also collect metrics regarding download / upload times, but that would be another PR.

**Comment by Narsil** [comment]
> which should not slow down the download noticeably).

**should** important word here :).

Giving information back to Python -> GIL most likely going to be an issue
Using indicatif -> Pulls in dependencies and we have to make sure it's not slowing anything down (now *and* later and on all weird platforms). 
There are ways to circumvent colab, but I remember it being a pain (different things between colab/jupyter and their relative versions). I think in tokenizers the progressbar are just disabled iirc.
 
 For statistics, couldn't you maintain them in user code (aka, not in this lib) ?

**Comment by Narsil** [comment]
And just because I'm curious I went to check if there was any known issues: https://github.com/console-rs/indicatif/issues/170

**Comment by McPatate** [comment]
> And just because I'm curious I went to check if there was any known issues: https://github.com/console-rs/indicatif/issues/170

Ofc a lock will incur a performance hit on hot path by creating high contention. With channels and a separate `spawn_blocking` thread you, again, shouldn't have the issue (not saying there is no overhead, just saying it won't cause the contention issue you get with a mutex / spinlock / wtv).

Regarding making the progress bar optional, it can simply be a function parameter that defaults to false, instead of trying to guess the platform / runtime environment.
And giving back info to python is clearly not an option, no.

There are 3 dependencies on indicatif:
```toml
console = { version = "0.15", default-features = false, features = ["ansi-parsing"] }
number_prefix = "0.4"
portable-atomic = "1.0.0"
```
There is an optional feature for tokio which we would probably be using were we to add the pb.

For statistics it's nothing concrete yet, so no need to think about it now, was just an idea.

I feel having a progress bar is typically something you would see on a download/upload tool. It's much better to have it in hf_transfer since we know when a chunk has finished downloading. We'd have to bench the overhead to know how much adding it impacts download speed, but imho this is negligible.

@dsully would you mind trying downloading a file on a machine with good disk & network bandwidth and sharing the results so we can see how much it impacts performance (w/ & w/out the pb) ? Thanks again for submitting the PR :)

**Comment by dsully** [comment]
Here's a video showing a download from CivitAI in this case. My upstream is 10G fiber. Ignore the stall at the end of the downloads, their CDN is having some issues.

https://user-images.githubusercontent.com/22371/228959473-9c192dc3-009a-4a9e-8ca4-7a5ecd04c78e.mp4

**Comment by Narsil** [comment]
Sorry to be insistent, but we need several benchmarks.

Actually if you can provide the benchmarks, we could run in internally too in our clusters where we can get really good bandwidth (and check the limits)

**Comment by dsully** [comment]
@Narsil Wouldn't it be easier for you to download and build this PR to run the benchmarks you need?

`gh pr checkout https://github.com/huggingface/hf_transfer/pull/9`

**Comment by akx** [comment]
I think it might be better to expose a progress callback to the Python code, and have it deal with things however it likes?

**Comment by Narsil** [comment]
> I think it might be better to expose a progress callback to the Python code, and have it deal with things however it likes?

Same potential slowdown.
I'm not saying there is a slowdown, I'm saying it happens fast, and I don't want to spend too much time checking if yes or no we're seeing less performance.

It's perfectly fine imo to just ditch the progress bar altogether.

**Comment by Narsil** [comment]
Implemented as https://github.com/huggingface/hf_transfer/pull/14

See upcoming release (using a callback instead of direct progressbar, someone internally voluntereed to maintain should something happen with it)

**Pull request closed without merging**
